[package]
name = "fla_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fla_common = { path = "../fla_common" }
reqwest = "0.11.22"
